#!/usr/bin/env python3
"""
GitHub Pages Deployment Helper

This script provides Python-based GitHub API operations for deploying
knowledge graph visualizations to GitHub Pages.

It's called by deploy-to-github.sh for operations that are easier in Python.

Usage:
    python scripts/github/deploy_pages.py check-repo <username> <repo>
    python scripts/github/deploy_pages.py create-repo <username> <repo>
    python scripts/github/deploy_pages.py enable-pages <username> <repo>
"""

import os
import sys
import json
import requests
from typing import Dict, Optional


class GitHubPagesDeployer:
    """Helper class for GitHub Pages deployment operations"""

    def __init__(self, token: Optional[str] = None):
        self.token = token or os.getenv('GITHUB_TOKEN')
        if not self.token:
            raise ValueError("GITHUB_TOKEN environment variable not set")

        self.headers = {
            'Authorization': f'token {self.token}',
            'Accept': 'application/vnd.github.v3+json'
        }
        self.base_url = 'https://api.github.com'

    def check_repo_exists(self, username: str, repo_name: str) -> bool:
        """Check if a repository exists"""
        url = f'{self.base_url}/repos/{username}/{repo_name}'
        response = requests.get(url, headers=self.headers)
        return response.status_code == 200

    def create_repo(self, repo_name: str, description: str = None) -> Dict:
        """Create a new public repository"""
        url = f'{self.base_url}/user/repos'

        if description is None:
            description = "Knowledge Graph Visualizations - Auto-generated by knowledge-system"

        data = {
            'name': repo_name,
            'description': description,
            'public': True,
            'auto_init': False,
            'has_issues': False,
            'has_wiki': False,
            'has_projects': False
        }

        response = requests.post(url, headers=self.headers, json=data)

        if response.status_code == 201:
            return {'success': True, 'data': response.json()}
        else:
            return {
                'success': False,
                'error': response.json().get('message', 'Unknown error'),
                'status_code': response.status_code
            }

    def enable_github_pages(self, username: str, repo_name: str,
                           branch: str = 'gh-pages') -> Dict:
        """Enable GitHub Pages for a repository"""
        url = f'{self.base_url}/repos/{username}/{repo_name}/pages'

        data = {
            'source': {
                'branch': branch,
                'path': '/'
            }
        }

        response = requests.post(url, headers=self.headers, json=data)

        if response.status_code == 201:
            pages_data = response.json()
            return {
                'success': True,
                'url': pages_data.get('html_url', f'https://{username}.github.io/{repo_name}/')
            }
        elif response.status_code == 409:
            # Already exists - get current config
            response = requests.get(url, headers=self.headers)
            if response.status_code == 200:
                pages_data = response.json()
                return {
                    'success': True,
                    'already_enabled': True,
                    'url': pages_data.get('html_url', f'https://{username}.github.io/{repo_name}/')
                }
            else:
                return {'success': False, 'error': 'Pages exist but cannot retrieve config'}
        else:
            return {
                'success': False,
                'error': response.json().get('message', 'Unknown error'),
                'status_code': response.status_code
            }

    def get_user_info(self) -> Dict:
        """Get authenticated user information"""
        url = f'{self.base_url}/user'
        response = requests.get(url, headers=self.headers)

        if response.status_code == 200:
            user_data = response.json()
            return {
                'success': True,
                'username': user_data.get('login'),
                'name': user_data.get('name'),
                'email': user_data.get('email')
            }
        else:
            return {'success': False, 'error': 'Cannot authenticate'}


def main():
    """CLI interface for GitHub Pages deployment operations"""
    if len(sys.argv) < 2:
        print("Usage: python deploy_pages.py <command> [args]", file=sys.stderr)
        print("\nCommands:", file=sys.stderr)
        print("  check-repo <username> <repo>   - Check if repo exists", file=sys.stderr)
        print("  create-repo <username> <repo>  - Create new repo", file=sys.stderr)
        print("  enable-pages <username> <repo> - Enable GitHub Pages", file=sys.stderr)
        print("  get-user                       - Get authenticated user info", file=sys.stderr)
        sys.exit(1)

    command = sys.argv[1]

    try:
        deployer = GitHubPagesDeployer()

        if command == 'check-repo':
            if len(sys.argv) != 4:
                print("Usage: check-repo <username> <repo>", file=sys.stderr)
                sys.exit(1)

            username, repo = sys.argv[2], sys.argv[3]
            exists = deployer.check_repo_exists(username, repo)

            result = {'exists': exists}
            print(json.dumps(result))
            sys.exit(0 if exists else 1)

        elif command == 'create-repo':
            if len(sys.argv) != 4:
                print("Usage: create-repo <username> <repo>", file=sys.stderr)
                sys.exit(1)

            repo = sys.argv[3]
            result = deployer.create_repo(repo)

            print(json.dumps(result))
            sys.exit(0 if result['success'] else 1)

        elif command == 'enable-pages':
            if len(sys.argv) != 4:
                print("Usage: enable-pages <username> <repo>", file=sys.stderr)
                sys.exit(1)

            username, repo = sys.argv[2], sys.argv[3]
            result = deployer.enable_github_pages(username, repo)

            print(json.dumps(result))
            sys.exit(0 if result['success'] else 1)

        elif command == 'get-user':
            result = deployer.get_user_info()
            print(json.dumps(result))
            sys.exit(0 if result['success'] else 1)

        else:
            print(f"Unknown command: {command}", file=sys.stderr)
            sys.exit(1)

    except ValueError as e:
        print(json.dumps({'success': False, 'error': str(e)}))
        sys.exit(1)
    except Exception as e:
        print(json.dumps({'success': False, 'error': f'Unexpected error: {str(e)}'}))
        sys.exit(1)


if __name__ == '__main__':
    main()
